TypeScriptWebApp: Fix error error TS2583: Build:Cannot find name 'Set'. Do you need to change your target library? Try changing the `lib` compiler option to es2015 or later.